environment:
  nodejs_version: "11"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

build_script:
  - yarn build

test_script:
  - yarn test

cache:
  - "%LOCALAPPDATA%\\Yarn"
